language: cpp
compiler:
  - gcc
script:
  - cd ..
  - mkdir build
  - cd build
  - cmake ../protolang0 -DCMAKE_BUILD_TYPE=DEBUG
  - make -j2
  - ./test/test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libboost-all-dev
